# Generated by Django 2.2.14 on 2020-07-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
    ]
